micronaut:
  application:
    name: tame-api
  dataSource:
    url: jdbc:mysql://localhost:3306/tame_db
    pooled: true
    driverClassName: com.mysql.cj.jdbc.Driver
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    username: ${JDBC_USER:"user"}
    password: ${JDBC_PASSWORD:"password"}